apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: origins-cms-secrets
  namespace: jx
  annotations:
    secret.jenkins-x.io/replica: 'true'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: gcpSecretsManager
  projectId: corded-imagery-343815
  data:
    - name: DATABASE_URL
      key: pluto-origins-cms-secrets
      property: DATABASE_URL
      version: latest
    - name: SESSION_SECRET
      key: pluto-origins-cms-secrets
      property: SESSION_SECRET
      version: latest
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'origins-helmfile-resources'
      labels:
        secret.jenkins-x.io/replica-source: 'true'
    type: Opaque
